image: gitpod/workspace-base

tasks:

- name: Get OMAMer database
  init: |
    cd /workspace
    curl -L -O "https://oma-stage.vital-it.ch/All/LUCA.h5"
    mv LUCA.h5 oma-omark/working_dir/DB/

    # install mamba
    cd /workspace
    wget "https://github.com/conda-forge/miniforge/releases/download/24.3.0-0/Mambaforge-24.3.0-0-Linux-x86_64.sh"
    bash Mambaforge-24.3.0-0-Linux-x86_64.sh -b -p /workspace/mambaforge && rm Mambaforge-24.3.0-0-Linux-x86_64.sh
    /workspace/mambaforge/bin/mamba init bash

    # install omark
    source ${HOME}/.bashrc
    mamba create -n omark -c conda-forge python=3.9 -y
    mamba activate omark
    pip install omark

  command: |
    cd /workspace/oma-omark/working_dir
    /workspace/conda/bin/conda init bash
    echo 'conda activate omark' >> ${HOME}/.bashrc
    source ${HOME}/.bashrc 
vscode:
  extensions:
    - anwar.papyrus-pdf

workspaceLocation: "/workspace"

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
